name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      run: |
        docker build -t gcr.io/your-project-id/test-seeds:latest .
        docker push gcr.io/your-project-id/test-seeds:latest
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        PROJECT_ID: your-project-id

    - name: Deploy to Kubernetes
      uses: google-github-actions/deploy-to-gke@v2
      with:
        credentials: ${{ secrets.GKE_SA_KEY }}
        project_id: your-project-id
        cluster: your-cluster-name
        location: your-cluster-location
        manifest: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: test-seeds
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: test-seeds
            template:
              metadata:
                labels:
                  app: test-seeds
              spec:
                containers:
                - name: test-seeds
                  image: gcr.io/your-project-id/test-seeds:latest
                  ports:
                  - containerPort: 8080
        container_image_url: gcr.io/your-project-id/test-seeds:latest
